name: flutterapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pinput: ^1.2.0
  toggle_switch: ^1.2.0
  flutter_carousel_slider: ^1.0.8
  image_picker: ^0.8.4
  intl: ^0.17.0
  flutter_native_splash: ^1.2.3
  shared_preferences: ^2.0.7
  intro_slider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  uses-material-design: true

  assets:
    - assets/images/arrow_back.png
    - assets/images/google_btn.png
    - assets/images/popl_round.png
    - assets/images/src_assets_instagram.png
    - assets/images/src_assets_loginwithfb.png
    - assets/images/src_assets_popllogoapp.png
    - assets/images/background.png
    - assets/images/src_assets_analytics.png
    - assets/images/src_assets_peoplepro.png
    - assets/images/src_assets_peopleprofilled.png
    - assets/images/src_assets_proprofile.png
    - assets/images/src_assets_proprofilefilled.png
    - assets/images/src_assets_qrnew.png
    - assets/images/src_assets_read.png
    - assets/images/assets_menu.png
    - assets/images/rect.png
    - assets/images/src_assets_activategrey.png
    - assets/images/src_assets_bolt.png
    - assets/images/src_assets_buygrey.png
    - assets/images/src_assets_homegrey.png
    - assets/images/src_assets_logoutgrey.png
    - assets/images/src_assets_qrcodegrey.png
    - assets/images/src_assets_todos.png
    - assets/images/src_assets_tutorialgrey.png
    - assets/images/src_assets_xmark.png
    - assets/images/src_assets_poplxl.png
    - assets/images/src_assets_newband.png
    - assets/images/src_assets_chart.png
    - assets/images/src_assets_newbandactivateandroid.png
    - assets/images/src_assets_poplprobig.png
    - assets/images/src_assets_swap.png
    - assets/images/src_assets_unlimited.png
    - assets/images/src_assets_pen.png
    - assets/images/src_assets_usernewnew.png
    - assets/images/src_assets_facebook.png
    - assets/images/src_assets_linkedin.png
    - assets/images/src_assets_notavailable.png
    - assets/images/src_assets_number.png
    - assets/images/src_assets_pinterest.png
    - assets/images/src_assets_podcasts.png
    - assets/images/src_assets_safari.png
    - assets/images/src_assets_snapchat.png
    - assets/images/src_assets_soundcloud.png
    - assets/images/src_assets_spotify.png
    - assets/images/src_assets_tiktok.png
    - assets/images/src_assets_tinder.png
    - assets/images/src_assets_twitch.png
    - assets/images/src_assets_twitter.png
    - assets/images/src_assets_venmo.png
    - assets/images/src_assets_verifiedblue.png
    - assets/images/src_assets_whatsapp.png
    - assets/images/src_assets_yelp.png
    - assets/images/src_assets_youtube.png
    - assets/images/src_assets_embeddedvideoicon.png
    - assets/images/logo.png
    - assets/images/popl.gif
    - assets/images/popl_qr.png
    - assets/images/popl_direct.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
